general:
  - url: https://itccorporation.netlify.app
    name: ITC Engineering Blog
    description: ITC Engineering Blog - Main Page
    #logo: /main.svg
    logo: /homelogo.png
    hashtag: blog_itc
    per_page: 2
    github: https://github.com/itc-tasho
blogs:
  - url: https://itccorporation.netlify.app/blogs
    logo: /bloglogo.png
    description: ITC Engineering Blog -
    type: article
    authors: ITC Engineering Blog
    images:
# ツイッターカード画像
        - url: https://itccorporation.netlify.app/blog.png
          width: 600
          height: 480
          alt: ITC Engineering Blog -
#        - url: /images/dummy.png
#          width: 600
#          height: 480
#          alt: ITC Engineering Blog -
